inrupt/pod-browser

- components/addFolderFlyout/__snapshots__/index.test.jsx.snap
- components/addFolderFlyout/index.jsx
- components/container/__snapshots__/index.test.tsx.snap
- components/containerPageHeader/__snapshots__/index.test.tsx.snap
This PR fixes a bug where actions in the Page Header in the Navigator didn't have proper margins.
> Setting proper margins for actions in ContainerPageHeader

- shapes/README.md
- shapes/bookmarks/bookmark.shex
- shapes/contacts/group-index.shex
> Suggestion for bookmark shapes

- components/addContact/__snapshots__/index.test.jsx.snap
- components/bookmarksList/__snapshots__/index.test.jsx.snap
- src/addressBook/index.js
- src/addressBook/index.test.js
- src/solidClientHelpers/utils.js
- src/solidClientHelpers/utils.test.js
In this PR:
- Fix bug in `chain` function causing it to not pass the options to `createThing`
- Add the correct `url` from the contact resource to the `peopleThing` before setting it in the `people.ttl`
This PR fixes bug #.
> Fix people index not pointing to the Person resource

- components/header/podIndicator/index.jsx
* Uses material-ui, as Prism does not have a "filled" variant for buttons
> Add submit button to pod navigator

- components/addContact/__snapshots__/index.test.jsx.snap
- components/addContact/index.jsx
- components/addContact/index.test.jsx
- components/addFolderFlyout/index.jsx
- components/addFolderFlyout/index.test.jsx
- components/addPermissionUsingWebIdButton/index.jsx
- components/addPermissionUsingWebIdButton/index.test.jsx
- components/agentSearchForm/__snapshots__/index.test.jsx.snap
- components/agentSearchForm/index.jsx
- components/agentSearchForm/index.test.jsx
- components/header/podIndicator/index.jsx
- components/header/podIndicator/index.test.jsx
- package-lock.json
Forms that has validation message added to them: 
- Pod Navigator (requires URL)
- Create folder (requires name)
- Adding WebID to Access Manager (requires WebId and at least one mode)
- Adding new contact (requires WebID)
Forms not added validation to
- Login (waiting for onSubmit functionality from Solid UI React)
- Managing existing WebID in Access Manager (WebID is given, removing all modes means removing agent from list)
> Adding validation message to all forms

- components/addFileButton/index.jsx
- components/addFileButton/index.test.jsx
With this PR we circumwent the problem with uploading files that starts with a dash by simply removing the initial dash.
> Handling uploaded files that starts with a dash

- package-lock.json
- package.json
- src/accessControl/acp/index.js
- src/accessControl/acp/index.test.js
Changed the appropriate API for the ACP features.
> Updated @inrupt/solid-client@0.6.2

- components/addContact/__snapshots__/index.test.jsx.snap
- components/addFileButton/__snapshots__/index.test.jsx.snap
- components/addFolderFlyout/__snapshots__/index.test.jsx.snap
- components/addPermissionUsingWebIdButton/__snapshots__/index.test.jsx.snap
- components/bookmarksList/__snapshots__/index.test.jsx.snap
- components/contactsList/__snapshots__/index.test.jsx.snap
- components/header/__snapshots__/index.test.jsx.snap
- components/header/mainNav/__snapshots__/index.test.jsx.snap
- components/header/menuDrawer/__snapshots__/index.test.jsx.snap
- components/header/userMenu/__snapshots__/index.test.jsx.snap
- components/login/__snapshots__/index.test.jsx.snap
- components/login/provider/__snapshots__/index.test.jsx.snap
- components/logout/__snapshots__/index.test.jsx.snap
- components/pages/access-required/__snapshots__/index.test.jsx.snap
- components/pages/contacts/show/__snapshots__/index.test.jsx.snap
- components/pages/index/__snapshots__/index.test.jsx.snap
- components/pages/login/__snapshots__/index.test.jsx.snap
- components/pages/profile/__snapshots__/index.test.jsx.snap
- components/profile/__snapshots__/index.test.jsx.snap
- components/profile/contactInfoTable/__snapshots__/index.test.jsx.snap
- components/resourceDetails/__snapshots__/index.test.jsx.snap
- components/resourceDetails/resourceSharing/agentAccess/__snapshots__/index.test.jsx.snap
- components/resourceDetails/resourceSharing/agentAccessList/__snapshots__/index.test.jsx.snap
- components/resourceDrawer/__snapshots__/index.test.jsx.snap
- package-lock.json
- package.json
Needed to upgraded authn client too it seems, so I updated @inrupt/solid-ui-react to the NPM tag that has that upgrade.
> Upgraded @inrupt/solid-client@0.6.3

- package-lock.json
- package.json
- pages/_app.jsx
This adds Matomo tracking, if the appropriate environment variables are configured. It uses an open-source React integration published by the [City of Amsterdam](https://github.com/Amsterdam/matomo-tracker#readme).
> Optional Matomo tracking

- components/resourceDetails/resourceSharing/agentAccess/index.jsx
Will write a test for this as part of improving test coverage (a bit dependent on the changes of enzyme --> testing-library for now)
> Tiny change that allows for saving un-modified permissions

- components/resourceDetails/resourceSharing/agentAccess/__snapshots__/index.test.jsx.snap
- components/resourceDetails/resourceSharing/agentAccess/index.jsx
- components/resourceDetails/resourceSharing/agentAccess/index.test.jsx
- src/accessControl/acp/index.js
- src/accessControl/acp/index.test.js
- src/accessControl/wac/index.js
- src/accessControl/wac/index.test.js
- Removing fetching of profiles in Access Control strategies
- Using SWR caching when fetching profiles in AgentAccess component
> Moved fetching of profiles to AgentAccess (+ making use of SWR caching)

- src/accessControl/acp/index.js
- src/accessControl/acp/index.test.js
Notes: You'll have to set explicit access to the various resources (inheritance isn't working yet).
> Fix to allow sharing of resources on ESS

- package-lock.json
- package.json
Was done earlier, must have been readded in a merge
> Removing enzyme related libraries

- components/containerPageHeader/__snapshots__/index.test.jsx.snap
- components/containerPageHeader/index.test.jsx
- components/containerPageHeader/styles.js
- components/podIndicator/__snapshots__/index.test.jsx.snap
- components/podIndicator/index.jsx
- components/podIndicator/index.test.jsx
- components/podIndicator/podNavigatorPopover/__snapshots__/index.test.jsx.snap
- components/podIndicator/podNavigatorPopover/index.jsx
- components/podIndicator/podNavigatorPopover/index.test.jsx
- components/podIndicator/podNavigatorPopover/styles.js
- components/podIndicator/styles.js
- Separate pod navigator into a component
- Style changes
- Tests updates
> Feat: pod indicator reformat

- constants/provider.js
This PR adds Inrupt Pod Spaces to list of IdPs
> Adding Inrupt Pod Spaces as Idp

- constants/__snapshots__/provider.test.js.snap
- constants/provider.test.js
Since https://github.com/inrupt/pod-browser/pull/208 didn't have a test, thought I should add one.
> Wrote a test for getIdentityProviders

- components/podIndicator/podNavigatorPopover/index.jsx
- components/podIndicator/podNavigatorPopover/index.test.jsx
This PR fixes: slashes added to resource urls.
We now:
- use the source url from the resource info when available
- if not available use the submitted url with trailing slashes (to be able to display an error page)
> fix: trailing slashes in pod navigator

- components/profile/__snapshots__/index.test.jsx.snap
- components/profile/contactInfoTable/__snapshots__/index.test.jsx.snap
- components/profile/contactInfoTable/index.jsx
- components/profile/contactInfoTable/index.test.jsx
- components/profile/index.jsx
- components/profile/index.test.jsx
Also improved test coverage for files I've touched.
> Adding missing testids for profile

- components/agentSearchForm/index.jsx
- components/agentSearchForm/index.test.jsx
> Fixed AgentSearchForm for adding new contacts

- components/addContact/__snapshots__/index.test.jsx.snap
- components/addContact/index.jsx
- components/addContact/index.test.jsx
- components/addPermissionUsingWebIdButton/index.jsx
- components/agentSearchForm/__snapshots__/index.test.jsx.snap
- components/agentSearchForm/index.jsx
- components/agentSearchForm/index.test.jsx
- components/pages/contacts/add/__snapshots__/index.test.jsx.snap
This PR fixes bug: incorrect error message when adding oneself as contact.
> Fix: error message when adding oneself as contact

- __testUtils/withTheme.jsx
- components/resourceDetails/index.jsx
- components/resourceDrawer/index.jsx
- components/resourceDrawer/index.test.jsx
- src/featureFlags/index.js
- src/featureFlags/index.test.js
Example of how to implement feature flags. Ignore all the old stuff I deleted. Couldn't help myself.
> Feature flags

- components/profile/contactInfoTable/__snapshots__/index.test.jsx.snap
- components/profile/contactInfoTable/index.jsx
- components/profile/contactInfoTable/index.test.jsx
- components/profile/index.jsx
- package-lock.json
- package.json
- Set/reset the data-testid's on the Profile page so TestCafe can differentiate between email addresses and phone numbers.
- Updated tests.
- Renamed "Company" to "Organization".
> Reset Profile data-testid's

- package-lock.json
- package.json
Upgrade solid-client-authn-browser to 1.6.0
> chore: upgrade solid-client-authn-browser to 1.6.0

- src/featureFlags/index.js
Added a webId to the list with access to features
> Adding a webid to the list with access to features

- components/confirmationDialog/index.jsx
- components/confirmationDialog/index.test.jsx
- components/resourceDetails/resourceSharing/agentAccess/agentAccessOptionsMenu/index.jsx
- components/resourceDetails/resourceSharing/agentAccess/agentAccessOptionsMenu/removeButton/index.jsx
- components/resourceDetails/resourceSharing/agentAccess/agentAccessOptionsMenu/removeButton/index.test.jsx
- components/resourceDetails/resourceSharing/agentAccess/agentProfileDetails/index.jsx
- constants/propTypes.js
- src/contexts/confirmationDialogContext/index.jsx
In this PR:
- fix remove 'undefined' bug in confirmation dialog
- allow setting a the text in confirmation dialog buttons
- bypass confirmation dialog for public and authenticated agents
- update tests
> Fix: remove 'undefined'

- components/addFileButton/index.jsx
- components/addFileButton/index.test.jsx
- components/pages/profile/__snapshots__/index.test.jsx.snap
- components/pages/profile/index.test.jsx
This PRs adds tests for:
- `addFileButton`
- `profile`
in order to improve test coverage.
> Fix: adding tests to improve coverage

- pages/_app.jsx
- Temporarily disabling session restore due to a bug
> Fix: disable session restore

- components/login/provider/index.test.jsx
This PR fixes code coverage after a previous merge into the main branch
> mocked checkOidc return value

- shapes/profile/app.shex
- shapes/profile/person.shex
This PR adds the profile shapes for person and app for documentation purposes.
- add person profile shape (pulled from ShapeRepo)
- add app profile shape
> Feat: add profile shapes

- __testUtils/mockConsentRequestDetails.js
- components/confirmationDialog/index.jsx
- components/confirmationDialog/index.test.jsx
- components/consentRequestForm/__snapshots__/index.test.jsx.snap
- components/consentRequestForm/dateInput/index.jsx
- components/consentRequestForm/index.jsx
- components/consentRequestForm/index.test.jsx
- components/consentRequestForm/purposeCheckBox/__snapshots__/index.test.jsx.snap
- components/consentRequestForm/purposeCheckBox/index.jsx
- components/consentRequestForm/purposeCheckBox/index.test.jsx
- components/consentRequestForm/purposeCheckBox/styles.js
- components/consentRequestForm/requestSection/__snapshots__/index.test.jsx.snap
- components/consentRequestForm/requestSection/index.jsx
- components/consentRequestForm/styles.js
- components/pages/privacy/consent/requests/__snapshots__/index.test.jsx.snap
- src/contexts/confirmationDialogContext/index.jsx
- src/models/consent/request/index.js
In this PR:
- add multiple purposes checkboxes
- confirmation dialog when no purpose is selected
- add tests
> Feat: multiple purposes

- src/hooks/useAllPermissions/index.js
The default states for consentPermisisons and acpPermissions were both empty arrays. If they continued to be empty even after getAllPermissionsforResource was called, the effect would not be called because the parameters did not change.
I started by replacing the empty arrays in the useStates with null, then realized that normalizeConsentBasedPermissions can be called outside of the effect. So instead, I removed most of the state, put that in a memo so that it doesn't recalculate unless consentBasedPermissions changes, and set the permissions based on the normalized permissions + consent permissions.
> Clean up useAllPermissions hook

- components/consentRequestForm/index.jsx
- components/consentRequestForm/index.test.jsx
> Fix: handle single purposes in an array

- components/resourceDetails/resourceSharing/addAgentButton/index.jsx
> [DRAFT] WebId edit field closes when user clicks "Cancel"

- package-lock.json
- package.json
This upgrades solid-client-authn to 1.11.5.
> Upgrade solid-client-authn to 1.11.5

- README.md
This PR does not introduce any code changes.
> Fix a minor typo in the README file

- .github/pull_request_template.md
- README.md
This PR makes a change to the PR template. The template contains the skeleton which encourages more explicit communication about what has changed, why, and how can it be verified. The proposed template is itself being employed in this PR to serve as an example.
- Updated the pull request template
- Minor spacing changes on README.md
- Make a pull request
- Verify you see the new pull request template
@solid-akb @VirginiaBalseiro 
I made this PR to start a discussion about whether or not a template like this would be helpful. I've used this in the past and I really like how the different sections walk you through making a good PR. I'm certainly open to any thoughts, complaints, etc. I don't want to just show up and change a bunch of things if they're working just fine how they are.
> Change pull request template

- components/container/index.jsx
- package-lock.json
This PR is just some minor cleanup I couldn't resist. It was pulled from another PR. I removed some of the logic from the JSX section of the component to be pulled up in a place where the logic is easier to read and reason about.
- Added a predicate function to clear up the logic regarding a missing iri
- Added a function that can conditionally render the spinner or the content of the container
- Added a function to contain the logic of possibly rendering a warning message
- Pure refactor, there should not be any noticeable changes.
@VirginiaBalseiro 
This was pulled from [another PR](https://github.com/inrupt/pod-browser/pull/430) by @VirginiaBalseiro's request. This also represents a bit of a style preference. I tend to prefer all logic be done outside of the JSX block in the return …
> Conatiner component cleanup

- components/pages/login/__snapshots__/index.test.jsx.snap
- components/pages/login/index.jsx
- components/pages/login/styles.js
- components/surveyWidget/__snapshots__/index.test.jsx.snap
- components/surveyWidget/index.jsx
- components/surveyWidget/index.test.jsx
- components/surveyWidget/widgetBox/index.jsx
- components/surveyWidget/widgetBox/styles.js
- components/surveyWidget/widgetButton/index.jsx
- components/surveyWidget/widgetButton/styles.js
- package-lock.json
This PR adds a button to the login page which opens a widget containing a link to the PodBrowser research survey.
New feature added to the login page as describes above
- Navigate to login page and find the button at the bottom of the page (test mobile and desktop according to acceptance criteria)
- Test widget displays properly, link works as intended, and close button/outside click closes the widget
- Test it is keyboard accessible
> Feat: add research survey widget

- package-lock.json
- package.json
Updated solid-client to have access to universalAccess and other things
> updated solid-client

- components/resourceDetails/resourceSharing/agentAccess/agentAccessOptionsMenu/consentDetailsButton/consentDetailsModal/index.test.jsx
- components/resourceDetails/resourceSharing/agentAccess/agentAccessOptionsMenu/consentDetailsButton/index.test.jsx
- components/resourceDetails/resourceSharing/agentAccessTable/__snapshots__/index.test.jsx.snap
- components/resourceDetails/resourceSharing/agentAccessTable/index.jsx
Was going to be to fix the bug but after deprioritizing still wanted to get some cleanup code in there. 
There was some logic and nested ternaries that I think may have caused some unintended loading states. This PR cleans that up. Also there were a few tests that had the wrong props being sent in that have been fixed. 
All tests pass.
Mini snippet of logic below: For example in line 159, if page was still loading it would go to the second return in the ternary even if there was no data.
> Clean up for Loading state and tests

- .github/workflows/ci.yml
- README.md
Add concurrency to the CI workflow. Now if more than one commit is made to the same branch, github will stop the existing CI process and start a new one.
> added concurrency to workflow

- components/surveyWidget/widgetBox/index.jsx
Fixed prop error on Survey widget
> fixed PropType errors

- package-lock.json
- package.json
> updated solid-client to 1.23

- package-lock.json
- package.json
> chore: upgrade to latest release

- components/accessRequestForm/index.jsx
- components/accessRequestForm/index.test.jsx
- components/pages/privacy/access/requests/generate-access-request/index.jsx
- package-lock.json
- package.json
This updates the hardcoded VC query parameter used in the access grant redirect flow to use a variable exported by the access-grants library.
> Update VC query param for access grants

- components/login/__snapshots__/index.test.jsx.snap
- components/login/index.jsx
- components/login/index.test.jsx
Adding back the original login button functionality 
Removed the message that displays when users click the login button and allows them to complete login
Removed test case for disabled button
> Re enable login on podspaces

- pages/api/app.js
- pages/api/app.test.js
Rebase and slight modifications to work done in the PR #477 
Adding test for  value of the client id itself, the presence of the offline_access, openid and webid scopes, the support for the authorization_code and the refesh_token grants
> Fix:update request to support refresh tokens

- components/accessRequestForm/__snapshots__/index.test.jsx.snap
- components/accessRequestForm/dateInput/index.jsx
- components/accessRequestForm/index.jsx
- components/accessRequestForm/index.test.jsx
- components/pages/privacy/access/requests/__snapshots__/index.test.jsx.snap
- package.json
This PR switches date picker to datetime picker for access requests.
- Generate an access request and verify changing time works as expected
> Feat: datetime picker in access request

- components/containerPageHeader/__snapshots__/index.test.jsx.snap
- components/podIndicator/__snapshots__/index.test.jsx.snap
- components/podIndicator/index.jsx
- components/podIndicator/styles.js
[Various text updates.](https://inrupt.atlassian.net/browse/APPS-1310) NEEDS UI REVIEW - DO NOT MERGE
Changed “Your Pod” to “Current Location”
Changed “Bookmark Pod” to “Bookmark Location”
Changed “Change Pod” to “Change Location”## Testing
> text updates in location dropdown area -  NEEDS UI REVIEW
