inrupt/pod-browser

- components/addFileButton/__snapshots__/index.test.jsx.snap
- components/addFileButton/index.jsx
- components/addFileButton/index.test.jsx
- components/container/__snapshots__/index.test.tsx.snap
- components/container/index.tsx
- components/containerPageHeader/__snapshots__/index.test.tsx.snap
- components/containerPageHeader/index.tsx
This PR fixes authentication errors when navigating into a container created in Data Browser.
These errors where mainly caused by passing URI-decoded resource names/URIs in different places.
Once one error was thrown, there were auth errors on all subsequent requests.
Also in this PR: 
- Slightly refactored AddFileButton to eliminate an unnecessary fetch (which was also throwing auth errors).
- Updated tests and snapshots
> Fix: authentication errors 

- components/detailsContextMenu/__snapshots__/index.test.jsx.snap
- components/resourceDetails/__snapshots__/index.test.tsx.snap
- components/resourceDetails/index.test.tsx
- components/resourceDetails/index.tsx
This PR changes the display names for resources in the Resource Details from the encoded full path name to just the decoded name of the resource, matching the displayed names in the Files container/list:
> Display decoded names in Resource Details

- src/solidClientHelpers/resource.js
- src/solidClientHelpers/resource.test.js
This PR fixes a regression that undid the work merged with https://github.com/inrupt/pod-browser/pull/81/
In this PR:
- added back the changes to the `getResourceName` function.
- added back the updated tests.
> fix: uri decoding names regression

- components/breadcrumbs/__snapshots__/index.test.jsx.snap
- components/breadcrumbs/index.jsx
This PR fixes broken breadcrumbs links causing 401 errors when navigating upwards between containers.
The error was caused by missing slashes at the end of links.
> Fix: add slash at the end of breadcrumb links to prevent auth errors

- __testUtils/createContainer.js
- __testUtils/createDataset.js
- components/detailsContextMenu/index.test.jsx
- components/header/mainNav/styles.ts
- components/header/styles.ts
- components/header/userMenu/styles.ts
- components/permissionsForm/index.test.jsx
- components/permissionsForm/styles.ts
- components/resourceDetails/resourceSharing/index.jsx
- components/resourceDetails/resourceSharing/index.test.jsx
- components/resourceDetails/styles.ts
- package-lock.json
- package.json
- pages/styles.css
- src/addressBook/index.js
- src/addressBook/index.test.js
- src/hooks/solidClient/index.js
- src/hooks/solidClient/index.test.js
- src/solidClientHelpers/permissions.js
- src/solidClientHelpers/permissions.test.js
- src/solidClientHelpers/profile.js
- src/solidClientHelpers/profile.test.js
- src/solidClientHelpers/resource.js
- src/solidClientHelpers/resource.test.js
- src/solidClientHelpers/utils.js
- src/solidClientHelpers/utils.test.js
This PR replaces calls to deprecated functions from solid-client by their replacements. There are a number of errors thrown when running the tests, but that already was the case before my changes, so I presume that that's normal. Other than that, all the tests succeed again.
> Migrate away from deprecated solid-client funcs

- src/contexts/alertContext/__snapshots__/index.test.jsx.snap
- src/contexts/alertContext/index.jsx
In this PR: 
- Added back alertSuccess and alertError to AlertContext
- Changed "success" to "error" in alertError
> Fix: error handling regression in addContact

- components/bookmark/index.jsx
- components/containerTableRow/index.test.jsx
- src/solidClientHelpers/bookmarks.js
Changes from previous PR:
- remove unnecessary check for `listOfRecallsUrls`
- update tests 
- save hardcoded IRIs in exported constants
> remove unnecessary check and save handcoded iris in constants

- pages/_app.tsx
- src/contexts/featureFlagsContext/index.jsx
- src/contexts/featureFlagsContext/index.test.jsx
- src/featureFlags/index.js
- src/featureFlags/index.test.js
- src/hooks/useFeatureFlags/index.js
- src/hooks/useFeatureFlags/index.test.jsx
I ended up rewriting everything and simplifying feature flags instead of pulling in a library for it.
* Specify rules in src/featureFlags, which are functions which receive a session and any extra context you pass in to the `enabled` or `useFeature` functions
* In components, use `useFeature("feature-key")` which returns a boolean.
* In components, optionally use `useFeature("feature-key", { whatever: "some-value" })` if you need to pass additional data to a feature flag function.
Example:
```
import { WAC_ENABLED } from "../src/featureFlags";
function WACEnabledIndicator() {
const wacEnabled = useFeature(WAC_ENABLED);
return wacEnabled ? "yes" : "no";
}
```
This seems like a bit of overkill still (why not just call wacEnabled() directly?) but it'll make more sense once we need session …
> Feature flags

- components/header/__snapshots__/index.test.jsx.snap
- components/header/userMenu/__snapshots__/index.test.jsx.snap
- components/header/userMenu/index.tsx
- components/header/userMenu/styles.ts
Added a "Files" link to the header leading to the pod root/files navigator.
> Add a Files link to the header nav leading to the pod root/files navigation view

- package-lock.json
- package.json
- pages/styles.css
https://www.npmjs.com/advisories/1565 recommends upgrading to 9.5.4 of Next, and we needed to fix the paths to fonts after upgrading.
> Upgrading Next to 9.5.4

- __testUtils/mockFetch.js
- src/solidClientHelpers/profile.js
This PR fixes bug #SOLIDOS-502.
To test: Add a WebID to the address book. You should see the avatar and name. (Before the bug it only showed the avatar.)
> Fixing faulty WebIDs being added to address book

- components/resourceDrawer/__snapshots__/index.test.jsx.snap
- components/resourceDrawer/index.jsx
- components/resourceDrawer/index.test.jsx
This PR fixes errors when trying to access subfolders with spaces by encoding the iri before fetching.
- Create a folder and a subfolder within it, both with names that contain spaces.
- Verify that you can navigate into the subfolder without errors.
> Fix: encode resource iri before fetching

- components/header/userMenu/index.jsx
- components/header/userMenu/index.tsx
- components/header/userMenu/styles.js
This PR fixes the user menu flickering when hovering on log out button after having clicked the user menu button.
This is fixed by separating the open and close actions for the hover, and toggling only on click.
> Fix: user menu flickering

- components/addFolderFlyout/__snapshots__/index.test.jsx.snap
- components/addFolderFlyout/index.jsx
- components/addFolderFlyout/index.test.jsx
- components/addFolderFlyout/styles.js
- components/container/__snapshots__/index.test.jsx.snap
- components/containerPageHeader/__snapshots__/index.test.jsx.snap
- components/permissionsForm/styles.js
- components/resourceDetails/resourceSharing/agentAccess/__snapshots__/index.test.jsx.snap
- components/resourceDetails/resourceSharing/agentAccess/index.jsx
- components/resourceDetails/resourceSharing/agentAccess/index.test.jsx
I've added onSubmit handling (and removed the existing onClick handling) for
- Create folder
- Managing existing access for an agent
There is a form that I haven't fixed yet, because I'm waiting for a fix in the Solid UI React. I'll create a separate PR for it later.
I also checked the following forms, which was already fixed:
- Pod Navigator
- Adding new contact
> Adds onSubmit to forms that are missing it

- components/addFileButton/index.jsx
- components/addFileButton/index.test.jsx
- components/addFolderFlyout/index.jsx
- components/addFolderFlyout/index.test.jsx
- components/breadcrumbs/index.jsx
- components/container/index.jsx
- components/deleteResourceLink/index.jsx
- components/header/index.test.jsx
- components/pages/resource/__snapshots__/index.test.jsx.snap
- components/pages/resource/index.jsx
- components/resourceDrawer/index.jsx
- src/hooks/useContainerResourceIris/index.js
- src/hooks/usePodOwnerProfile/index.js
- src/hooks/usePodOwnerProfile/index.test.jsx
This PR fixes bug: Various functions involving files and folders with special characters:
- Folders with special characters in name
- Creating
- Navigating to
- Deleting
- Files with special characters in name
- Uploading
- Opening drawer for resource
- Deleting
I've been using the following list when creating new folders:
- -initial-colon-final-
- :initial:colon:final:
- before[between]after
- colon:medial
- coma,comma
- LeHégaret
- movie@11
- now two spaces
- one space
- per%cent
I've also used files with corresponding names, except that colons are replaced with dashes. I've attached a ZIP file with the files included.
[files-with-problematic-characters.zip](https://github.com/inrupt/pod-browser/files/5430617/files-with-problematic-characters.zip)
> Cleaning up the use of encoded URIs

- components/header/podIndicator/__snapshots__/index.test.jsx.snap
- components/header/podIndicator/index.jsx
- components/header/podIndicator/styles.js
- Adds max width to pod indicator name, with ellipsis cutoff
- Adds title attribute to button, with full name
Explored solutions wrapping the pod name — however, the headers in Prism are a fixed height 100px, which means there isn’t room for even a second line without shuffling things. _Could_ allow the header to grow vertically, but either it could do so indefinitely, or we’d probably want to truncate the name at some point anyway.
> Add ellipsis cutoff to long names in podIndicator

- components/header/podIndicator/styles.js
This PR fixes the pod navigator going off the screen when the keyboard comes up in iOS devices.
**Note**: needs to be tested on an actual iOS device (not browser emulators).
- Open the Vercel preview in a mobile device (iPhone)
- Open the Pod Navigator
- Start typing
- Verify that the PodNavigator is still fully  visible and usable
> adding a maxWidth for small screens

- components/contactsList/__snapshots__/index.test.jsx.snap
- components/contactsList/index.jsx
- Adds name as alt text for contact avatar
- Descriptive alt text means fallback image used by Material UI Avatar is appropriate
- Leaves alt as "Contact avatar" when name value is missing
> Add name as alt text for contact avatar

- components/header/__snapshots__/index.test.jsx.snap
- src/hooks/usePodOwner/index.js
- src/hooks/usePodOwner/index.test.js
- src/hooks/usePodOwnerProfile/index.js
- src/hooks/usePodOwnerProfile/index.test.jsx
This enables the pod indicator to use pod owner when available, or fall back to fetching the profile from the constructed profile iri. 
- Log in with an ESS and check that the owner name is displayed properly
- Do the same with an NSS account to check that the fallback works
> Feat: add pod ownership to useOwnerProfile hook

- components/header/menuDrawer/index.jsx
- components/header/menuDrawer/styles.js
This PR adds the Profile link to the hamburger menu in mobile.
Matched the link style to the Logout link since we don't have "Profile" in the design, and made sense to put it after the divider along with Logout since it's part of the user menu items.
> Fix: add Profile link to hamburger menu in mobile

- components/bookmarksList/index.jsx
This PR fixes blank bookmark added to ESS pods.
The ESS server injects a triple with the type of resource in the `index.ttl` which the table was trying to render as a bookmark. This PR fixes that by filtering by type before creating the bookmark array in order to make sure we only have bookmarks.
- Log in with https://broker.pod.inrupt.com
- Verify that there is no longer a blank bookmark added
> Fix: filter bookmarks by type

- components/login/__snapshots__/index.test.jsx.snap
- components/login/provider/__snapshots__/index.test.jsx.snap
- components/login/provider/index.jsx
- components/pages/login/__snapshots__/index.test.jsx.snap
This PR fixes:
- Random client id displayed instead of client name in client registration requests
- login with ESS
- verify that "Pod Browser" is now displayed instead of randomly generate client id (see screenshot below)
> Fix: pass client name in authOptions to Login button

- __testUtils/mockContactResource.js
- __testUtils/mockPersonResource.js
- components/addContact/index.jsx
- components/contactsList/__snapshots__/index.test.jsx.snap
- components/contactsList/contactsListSearch/__snapshots__/index.test.jsx.snap
- components/contactsList/contactsListSearch/index.jsx
- src/addressBook/index.js
- src/addressBook/index.test.js
- src/hooks/usePeople/index.test.jsx
- src/solidClientHelpers/profile.js
- src/solidClientHelpers/profile.test.js
This modifies `saveContact` to map types to container / file names.
We are currently storing all person contacts in “people.ttl” and the “People/” container. I have updated the code to allow for switching the index file and container name based on type of contact - which is currently pulled from the type of the profile (reading the Thing by foaf.primaryTopic or foaf.maker when defined.) If the profile is a foaf.Person (regardless of it it has multiple types), we treat it as a contact and add it to “people”, or otherwise we display an error message.
Using a specific file name (people.ttl, People/) is pretty hacky compared to including the contact type in an overall index file, but this maintains compatibility with databrowser.
> Make saveContact generic to type

- components/resourceDetails/__snapshots__/index.test.jsx.snap
- components/resourceDetails/index.jsx
- components/resourceDrawer/__snapshots__/index.test.jsx.snap
- Added data-testid to accordions
- Fixed unique data-testid to actions
> Fixed data-testid to accordions and action buttons in Resource Drawer

- components/addPermissionUsingWebIdButton/__snapshots__/index.test.jsx.snap
- components/addPermissionUsingWebIdButton/index.jsx
- components/permissionsForm/__snapshots__/index.test.jsx.snap
- components/permissionsForm/permissionCheckbox/__snapshots__/index.test.jsx.snap
- components/permissionsForm/permissionCheckbox/index.jsx
- components/resourceDetails/index.jsx
- components/resourceDetails/resourceSharing/__snapshots__/index.test.jsx.snap
- components/resourceDetails/resourceSharing/agentAccess/__snapshots__/index.test.jsx.snap
- components/resourceDrawer/__snapshots__/index.test.jsx.snap
> Added data-testid to Add user with WebID (and checkboxes)

- components/bookmarksList/styles.js
This PR fixes: bookmark list search box exceeding screen width in small devices.
The input box now has a max width (like the Contacts search input box) and a width.
> Fix: add min and max width to input

- components/container/__snapshots__/index.test.jsx.snap
- components/container/index.jsx
- components/containerTableRow/__snapshots__/index.test.jsx.snap
- components/containerTableRow/index.jsx
- src/stringHelpers/index.js
- src/stringHelpers/index.test.js
This PR fixes the issue of the "resource not supported" message when the clicking on a bookmarked resource that isn't a container, by navigating to the parent container, preselecting the row, and opening the drawer for the resource.
> Feat: bookmark links open parent container and resource details drawer

- components/deleteResourceLink/__snapshots__/index.test.jsx.snap
- components/deleteResourceLink/index.jsx
- components/deleteResourceLink/index.test.jsx
- components/resourceDrawer/__snapshots__/index.test.jsx.snap
- src/accessControl/acp/index.js
- src/accessControl/acp/index.test.js
- src/hooks/usePoliciesContainer/index.js
- src/hooks/usePoliciesContainer/index.test.js
- src/solidClientHelpers/policies.js
- src/solidClientHelpers/policies.test.js
- src/solidClientHelpers/resource.js
- src/solidClientHelpers/resource.test.js
This PR fixes the delay when trying to delete a resource (getting an error when clicking immediately after details drawer is loaded).
- create new deleteResource function that deletes a file and its corresponding policy (if available)
- remove deleteFile from access control
- update/add tests
> Fix: move deleteFile logic out of access control

- components/deleteResourceButton/index.jsx
- components/deleteResourceButton/index.test.jsx
- components/resourceDrawer/__snapshots__/index.test.jsx.snap
- src/solidClientHelpers/resource.js
- src/solidClientHelpers/resource.test.js
This PR fixes bug: cannot view resources.
Fix: switch useDataset for useResourceInfo to fix error with non-turtle resources
> Fix: switch useDataset for useResourceInfo

- components/addContact/index.jsx
- components/addContact/index.test.jsx
- components/contactsList/__snapshots__/index.test.jsx.snap
- components/contactsList/index.jsx
- components/contactsList/index.test.jsx
- src/addressBook/index.js
- src/addressBook/index.test.js
- src/hooks/useContacts/index.js
- src/hooks/useContacts/index.test.jsx
- src/solidClientHelpers/resource.js
The people index (`people.ttl`) is now used to show, save and delete contacts.
> refactoring to use index dataset

- src/accessControl/acp/index.js
- src/accessControl/acp/index.test.js
- src/accessControl/wac/index.js
- src/accessControl/wac/index.test.js
- src/contexts/accessControlContext/index.jsx
> Returning error if you don't have access to Access Control resources

- components/resourceDetails/__snapshots__/index.test.jsx.snap
- components/resourceDetails/index.jsx
- components/resourceDrawer/__snapshots__/index.test.jsx.snap
- src/accessControl/acp/index.js
- src/accessControl/acp/index.test.js
- src/accessControl/wac/index.js
- src/accessControl/wac/index.test.js
- src/contexts/accessControlContext/index.jsx
- src/hooks/useAccessControl/index.jsx
- src/hooks/useAccessControl/index.test.jsx
Builds upon the  work in https://github.com/inrupt/pod-browser/pull/183.
Also lifts the restriction of needing to have Control access to see Delete button.
> Making sure to refresh permissions + not requiring control to see delete

- pages/_app.jsx
This updates the matomo tracker to use the base path name (e.g. `/resource/[iri]`) instead of the full path (`/resource/iriurl?query=some-querystring`). The useEffect does watch full path changes to know when to send another page view.
> Update matomo tracker

- components/addPermissionUsingWebIdButton/index.jsx
- components/agentSearchForm/index.jsx
- components/agentSearchForm/index.test.jsx
- components/containerPageHeader/index.test.jsx
This PR fixes bug: users can still overwrite their own permissions by re-adding their webId.
We now display an error when the users tries to add themselves to the permissions, or a webId that is also in the permissions for that resource.
> Fix: disallow existing or own webId in permissions

- components/login/provider/index.jsx
- components/login/provider/index.test.jsx
- components/pages/login/index.test.jsx
- src/hooks/useIdp/index.js
- src/hooks/useIdp/index.test.js
- src/hooks/useIdpFromQuery/index.js
- src/hooks/useIdpFromQuery/index.test.js
- src/hooks/useQuery/index.js
- src/hooks/useQuery/index.test.js
- src/solidClientHelpers/utils.test.js
Can pass Idp to the login provider using a query param, e.g. `?idp=https%3A%2F%2Finrupt.net%2F`.
> Added support for passing IdP using query param

- components/podIndicator/podNavigatorPopover/__snapshots__/index.test.jsx.snap
- components/podIndicator/podNavigatorPopover/index.jsx
- components/podIndicator/podNavigatorPopover/index.test.jsx
This PR fixes: HEAD requests on input change on pod navigator
- <del>move the `useResourceInfo` to the handler</del> refactor to use `getResourceInfo` directly in the submit handler
- update tests
> Fix: move useResourceInfo into submit handler

- components/deleteResourceButton/index.jsx
- components/deleteResourceButton/index.test.jsx
- src/stringHelpers/index.js
- src/stringHelpers/index.test.js
This PR adds: 
- After deleting the current folder, PodBrowser navigates to the parent folder.
> fix: navigate to parent folder after deleting current folder

- components/addFileButton/__snapshots__/index.test.jsx.snap
- components/addFileButton/index.jsx
- components/addFileButton/index.test.jsx
- components/container/__snapshots__/index.test.jsx.snap
- components/containerSubHeader/__snapshots__/index.test.jsx.snap
- package-lock.json
- package.json
This PR adds:
- The "Upload File" button is now focusable
- The file browser opening is triggered by pressing "Enter"
> fix: focus on upload button and trigger file browser opening on enter

- __testUtils/mockPersonResource.js
- components/contactsList/index.jsx
- components/profile/index.jsx
- shapes/contacts/person.shex
- src/addressBook/index.js
- src/addressBook/index.test.js
- with new contacts, create a 'blank' node under `vcard.url`
- read from `foaf.openid` and `vcard.url`
- update tests
> Fix: use vcard.url instead of foaf.openid for new contacts

- components/containerDetails/index.jsx
- components/containerDetails/index.test.jsx
- components/deleteResourceButton/index.jsx
- components/deleteResourceButton/index.test.jsx
- components/resourceDetails/index.jsx
- components/resourceDrawer/index.jsx
- components/resourceDrawer/index.test.jsx
This PR fixes bug: pod indicator displays "unknown" after deleting current folder
The cause was redirecting to the deleted folder: `stripQueryParams` did not work in the case of the current folder because there are no query params to remove and we need to go up one level. When trying to fetch the pod owner for the resource requested, it cause an error which set the pod owner web to null.
> fix: handle deletion of current folder

- src/solidClientHelpers/policies.js
- src/solidClientHelpers/policies.test.js
In some rare cases we would get a double slash in the URLs for policy resources. This PR aims to fix that.
> Making sure we don't get policy resource URLs with double slashes

- __testUtils/mockBookmarks.js
- __testUtils/mockPersonContactThing.js
- __testUtils/mockPersonResource.js
- __testUtils/mockSession.js
- components/addContact/index.jsx
- components/bookmark/index.jsx
- components/bookmarksList/__snapshots__/index.test.jsx.snap
- components/bookmarksList/index.test.jsx
- components/contactsList/__snapshots__/index.test.jsx.snap
- components/contactsList/index.jsx
- components/resourceDetails/resourceSharing/agentAccess/__snapshots__/index.test.jsx.snap
- package-lock.json
- package.json
- src/accessControl/acp/index.js
- src/addressBook/index.js
- src/addressBook/index.test.js
- src/contexts/bookmarksContext/index.jsx
- src/hooks/useAddressBook/index.js
- src/hooks/useAddressBook/index.test.js
- src/hooks/useContactsContainerUrl/index.js
- src/hooks/useContactsContainerUrl/index.test.js
- src/hooks/usePoliciesContainer/index.js
- src/solidClientHelpers/utils.js
- src/solidClientHelpers/utils.test.js
This upgrade revealed some misuses of Solid Client in older modules (e.g. using `getUrl` with a `SolidDataset` instead of a `Thing`). This PR fixes all of these faulty uses.
> Upgrading solid client to 1.3.0

- __testUtils/mockPersonResource.js
- components/breadcrumbs/index.test.jsx
- components/container/index.jsx
- components/container/index.test.jsx
- package-lock.json
- package.json
- src/contexts/podLocationContext/index.jsx
- src/contexts/podLocationContext/index.test.jsx
- src/error/index.js
- src/error/index.test.js
- src/hooks/usePodOwner/index.js
- src/hooks/usePodOwner/index.test.js
- src/hooks/usePodOwnerProfile/index.js
- src/hooks/usePodRootUri/index.js
- src/hooks/usePodRootUri/index.test.jsx
- src/hooks/useResourceInfo/index.js
- src/hooks/useResourceInfo/index.test.js
- src/solidClientHelpers/profile.js
- src/solidClientHelpers/profile.test.js
This PR fixes a bug where you were shown an error message when you navigated to a resource on someone else's Pod, even though you had been given access to view that resource.
This PR builds upon https://github.com/inrupt/pod-browser/pull/238, so should be merged after it.
> Fixing bug where a warning message was always shown when visiting another user's Pod

- src/hooks/useDataset/index.js
- src/hooks/useDataset/index.test.jsx
I did this as part of chasing down a bug I found as part of my work on https://github.com/inrupt/pod-browser/pull/257, but realized I didn't need to push it there. But, improving test coverage is always nice, so wanted to push this in a separate branch.
> Improving test coverage for useDataset

- components/resourceDetails/resourceSharing/sharingAccordion/__snapshots__/index.test.jsx.snap
- components/resourceDetails/resourceSharing/sharingAccordion/index.jsx
- components/resourceDetails/resourceSharing/sharingAccordion/index.test.jsx
- src/accessControl/acp/index.js
- src/models/profile/index.js
In this PR:
- adding `applyMembers` to the ACR for all policies
- adding an info message to alert users about inheritance
- update tests
- fix a small bug where contact wasn't saved when adding it to a policy due to an unhandled error
> Revert "Revert "Feat/default inheritance""

- components/resourceDetails/resourceSharing/agentAccessTable/index.jsx
- src/accessControl/acp/index.js
- src/accessControl/acp/index.test.js
- add function to get inherited permissions
- modify getPermissions functions so that they return all the permissions that apply to the resource, including inherited ones
- add tests
> Feat: displaying inherited access

- components/addContact/__snapshots__/index.test.jsx.snap
- components/agentSearchForm/__snapshots__/index.test.jsx.snap
- components/agentSearchForm/index.jsx
- components/pages/contacts/add/__snapshots__/index.test.jsx.snap
This PR changes the pattern used for validation so that it checks not only that the WebId begins with `https://` but also that it does not contain spaces.
> fix: validate WebId when adding it to permissions

- components/resourceDetails/resourceSharing/agentAccess/agentAccessOptionsMenu/index.jsx
- components/resourceDetails/resourceSharing/agentAccess/agentProfileDetails/__snapshots__/index.test.jsx.snap
- components/resourceDetails/resourceSharing/agentAccess/agentProfileDetails/index.jsx
- components/resourceDetails/resourceSharing/agentAccess/agentProfileDetails/index.test.jsx
This PR hides the action button for agents who have inherited access, since we are not yet handling the removal of inherited access.
To test this, be are aware of the bug in inheritance which makes inherited access for the second policy added only accessible through a private browser window.
> Fix: hide action button for inherited access

- components/deleteButton/index.jsx
- components/deleteResourceButton/index.jsx
This PR fixes our error message when deleting a non-empty container to make it more understandable for users.
> fix: change error message when deleting a non-empty container

- components/addPermissionUsingWebIdButton/index.jsx
- components/permissionsForm/index.jsx
This PR fixes bug where the permissions "Add WebId" button would go off the screen when the content of the popover grows. The solution in this PR is to have the vertical growth start from the bottom of the popover, so it grows upwards vertically and it doesn't go off the screen.
Update: after discussion with @KyraAssaad we decided to always display the options for a new WebId to prevent the popover from repositioning when state changes.
> fix: anchor transform permission Add popover to the bottom

- components/resourceDetails/resourceSharing/agentPickerModal/index.jsx
- components/resourceDetails/resourceSharing/agentPickerModal/webIdCheckbox/index.jsx
- components/resourceDetails/resourceSharing/agentPickerModal/webIdCheckbox/index.test.jsx
- src/accessControl/acp/index.js
- src/accessControl/acp/index.test.js
This will disable checkboxes in the Sharing accordion (shown for servers that supports ACP) when the agent shown has gotten the permission through inherited policies (aka cascaded policies).
> Disabling checkboxes for permissions from inherited policies

- pages/_document.jsx
This PR removes an unnecessary style sheet link for a font.
> Chore: remove unnecessary font style sheet link

- components/resourceDetails/__snapshots__/index.test.jsx.snap
- components/resourceDetails/resourceSharing/addAgentButton/__snapshots__/index.test.jsx.snap
- components/resourceDetails/resourceSharing/addAgentButton/index.jsx
- components/resourceDetails/resourceSharing/agentAccessTable/__snapshots__/index.test.jsx.snap
- components/resourceDetails/resourceSharing/sharingAccordion/__snapshots__/index.test.jsx.snap
This PR fixes bug #.
Changing the icon add (+) to edit (a pencil) for "Edit [name of policy members]".
> Changed icon from + to pencil in "Edit [policy]"

- package-lock.json
- package.json
This PR upgrades `solid-client-authn-browser` to the latest version (1.8.0)
> upgrade solid-client-authn-browser to latest version

- components/container/index.jsx
- components/container/index.test.jsx
- package-lock.json
- package.json
- pages/_app.jsx
In this PR:
- upgrade to latest version of `solid-ui-react`
- pass `restorePreviousSession` to `SessionProvider` to restore session on browser refresh
- use `onSessionRestore` to redirect to navigated page
This PR fixes bug #SDK-2048.
> Fix: pass restorePreviousSession to SessionProvider 

- src/hooks/useAccessControl/index.jsx
- src/hooks/useAccessControl/index.test.jsx
This PR removes the dependency on `authenticatedProfile` in the `useAccessControl` hook, since it was not used and it was causing the details drawer to rerender (causing the blinking effect described in the issue).
It is unclear to me why this was added to the `useEffect`  dependencies, but it did not seem to cause any issues to remove it. 
This PR fixes bug #SDK-2050 and fixes #294.
> Fix: remove unnecessary dependency in hook causing rerenders

- components/resourceDetails/resourceSharing/agentAccessOld/index.jsx
In this PR:
- checking for confirmation dialog id before calling savePermissions for user changing their own permissions
We weren't checking if the confirmation dialog being confirmed was the permissions change dialog, so we were calling `savePermissions` every time any dialog was confirmed, which was causing a change in permissions before the folder was deleted. 
The confirmation dialog is particularly hard to test which is why we didn't catch this before, and we have a ticket to refactor it (using a simple dialog component instead of context wherever we need it). 
This PR fixes bug #SDK-2085.
> Fix: adding check for confirmation dialog

- components/addFileButton/index.jsx
- components/addFileButton/index.test.jsx
- components/confirmationDialog/index.jsx
- components/confirmationDialog/index.test.jsx
- components/deleteButton/index.jsx
- components/deleteButton/index.test.jsx
- components/resourceDetails/resourceSharing/agentAccess/agentAccessOptionsMenu/removeButton/index.jsx
- components/resourceDetails/resourceSharing/agentAccess/agentAccessOptionsMenu/removeButton/index.test.jsx
- components/resourceDetails/resourceSharing/agentAccess/index.jsx
- components/resourceDetails/resourceSharing/agentAccessOld/__snapshots__/index.test.jsx.snap
- components/resourceDetails/resourceSharing/agentAccessOld/index.jsx
- components/resourceDetails/resourceSharing/agentAccessOld/index.test.jsx
- components/resourceDetails/resourceSharing/agentPickerModal/index.jsx
- components/resourceDetails/resourceSharing/agentPickerModal/index.test.jsx
- components/resourceDetails/resourceSharing/policyActionButton/index.jsx
- components/resourceDetails/resourceSharing/policyActionButton/index.test.jsx
- pages/_app.jsx
- src/contexts/confirmationDialogContext/index.jsx
In this PR:
- use confirmation dialog in the components where it's needed, so that it is appended in a way that can be tested
- write tests for interactions with the confirmation dialog
- Verify that the confirmation dialog works as intended in all the places where it's used:
> Refactor: confirmation dialog

- src/addressBook/index.js
This PR fixes bug #SOLIDOS-906.
This PR fixes the issue of contacts adding the wrong iri for the address book. The fix is a temporary hack, the proper way of handling it is using the new address book model and getting the iri from there, which involves a refactor that turned out to be bigger than I expected so I will make a separate PR for that, since we're removing Contacts soon, and it's not a priority.
> Fix: address book iri

- next.config.js
- package-lock.json
- package.json
I was initially planning on just enabling source maps if `process.env.VERCEL_ENV !== "production"`, but then I saw that source maps were already supposed to be enabled always (using a package [that's now deprecated](https://www.npmjs.com/package/@zeit/next-source-maps)), so I just did so too.
(Yes, this is because my computer crawls to a halt when I try to run PodBrowser locally :P Unfortunately, it seems that this is not enough to have the React DevTools show me the full component names, but it still seems like a sensible change.)
> Use native Next.js source map functionality

- components/resourceDetails/resourceSharing/addAgentRow/__snapshots__/index.test.jsx.snap
- components/resourceDetails/resourceSharing/addAgentRow/index.jsx
- components/resourceDetails/resourceSharing/addAgentRow/index.test.jsx
This PR fixes bug #SOLIDOS-899.
- Added a check to display a validation error when the user tries to add themselves as an agent to a policy.
> Fix: disallow adding own WebID to permissions

- src/hooks/useUserMenu/index.js
- src/hooks/useUserMenu/index.test.js
This PR fixes bug #SOLIDOS-963.
In this PR:
- redirecting to login page after logout has completed in the user menu button
> Fix: redirect on logout

- __testUtils/mockApp.js
- __testUtils/mockGroup.js
- __testUtils/mockPersonContact.js
- __testUtils/mockPersonResource.js
- components/addContact/index.test.jsx
- components/agentList/index.jsx
- components/contactsList/index.jsx
- components/profile/appProfile/index.jsx
- components/profile/personProfile/index.jsx
- components/profileLink/index.jsx
- components/resourceDetails/resourceSharing/agentPickerModal/index.jsx
- src/addressBook/index.js
- src/addressBook/index.test.js
- src/featureFlags/index.js
- src/models/contact/group/index.js
- src/models/contact/group/index.test.js
- src/models/contact/index.test.js
- src/models/contact/person/index.js
- src/models/dataset/index.test.js
- src/models/group/index.js
- src/solidClientHelpers/profile.js
This PR changes the uses of `vcard.fn` to `foaf.name` throughout the app.
Verify that names are displayed correctly both on NSS and ESS for the following pages:
- User profile (own and contacts)
- Contacts
- Privacy
- Permissions (NSS)
- Sharing (ESS)
- Groups
> Switch vcard.fn to foaf.name

- __testUtils/mockLocalStorage.js
- components/pages/index/index.jsx
- components/pages/index/index.test.jsx
- components/pages/login/__snapshots__/index.test.jsx.snap
- components/pages/login/index.jsx
- components/pages/login/index.test.jsx
- pages/_app.jsx
- src/hooks/usePreviousPage/index.js
- src/hooks/usePreviousPage/index.test.jsx
This PR fixes bug #SOLIDOS-657.
- save previous page in localStorage to be able to redirect when logged out
- add usePreviousPage hook
- add tests
> Fix: redirect browser bookmark

- __testUtils/mockConsentRequestContext.jsx
- __testUtils/mockConsentRequestDetails.js
- __testUtils/mockPermissionsContextProvider.jsx
- components/consentRequestForm/__snapshots__/index.test.jsx.snap
- components/consentRequestForm/index.jsx
- components/consentRequestForm/index.test.jsx
- components/consentRequestForm/requestSection/__snapshots__/index.test.jsx.snap
- components/consentRequestForm/requestSection/index.jsx
- components/consentRequestForm/requestSection/index.test.jsx
- components/pages/privacy/consent/requests/__snapshots__/index.test.jsx.snap
- components/pages/privacy/consent/requests/index.jsx
- src/accessControl/acp/index.js
- src/models/consent/request/index.js
- src/solidClientHelpers/utils.js
In this PR: 
- Adding the confirmation dialog check when trying to accept a consent request without any selected access
- add tests
- minor fixes (test names, etc)
- moved some of the JSON-LD destructuring into functions in a consent model, so that it's easier to swap for solid-client functions once we do (since we shouldn't be relying on destructuring JSON-LD as the consent request can be something other than JSON-LD)
> Feat/consent UI accept request

- components/consentRequestForm/__snapshots__/index.test.jsx.snap
- components/consentRequestForm/index.jsx
- components/consentRequestForm/index.test.jsx
- components/pages/privacy/consent/requests/__snapshots__/index.test.jsx.snap
- displaying confirmation dialog when clicking on Deny All Access button, regardless of the state of the toggles
*Note*: this PR is based off https://github.com/inrupt/pod-browser/pull/325 and should be merged after it.
> Feat/consent UI reject request

- components/addFileButton/index.jsx
- components/container/index.jsx
- components/pages/login/index.jsx
- src/hooks/useContainer/index.js
- src/hooks/useContainer/index.test.js
This PR fixes bugs #SOLIDOS-977 and #SOLIDOS-981.
- Refactor `useContainer` hook to use useSWR so it revalidates after error cleared
- Added check to not display error message until it finished validating
- Update tests
> Fix: refresh container after error is cleared

- components/agentList/agentsDrawer/__snapshots__/index.test.jsx.snap
- components/agentList/index.jsx
- components/agentResourceAccessLink/__snapshots__/index.test.jsx.snap
- components/agentResourceAccessLink/index.jsx
- components/agentResourceAccessLink/index.test.jsx
- components/pages/privacy/resourceAccess/resourceAccessDrawer/__snapshots__/index.test.jsx.snap
- components/pages/privacy/resourceAccess/resourceAccessDrawer/index.jsx
- components/pages/privacy/resourceAccess/resourceAccessDrawer/index.test.jsx
- components/pages/privacy/resourceAccess/resourceAccessDrawer/styles.js
- components/pages/privacy/resourceAccess/show/index.jsx
- constants/policies.js
- pages/privacy/resourceAccess/[webId].jsx
- src/accessControl/acp/index.js
In this PR: adding drawer displaying details about ACP access
Not in this PR: 
- Edit access button
- Consent details info
- Some icons don't match the designs: these will be added to Prism and updated in PB in separate PRs.
- Ignore the resource for agents page: it will be replaces in another ticket
- # Checklist
> Feat: add ACP info drawer

- components/confirmationDialog/index.jsx
- components/confirmationDialog/styles.js
- components/pages/privacy/resourceAccess/resourceAccessDrawer/__snapshots__/index.test.jsx.snap
- components/pages/privacy/resourceAccess/resourceAccessDrawer/index.jsx
- components/pages/privacy/resourceAccess/resourceAccessDrawer/index.test.jsx
- components/pages/privacy/resourceAccess/resourceAccessDrawer/styles.js
- components/pages/privacy/resourceAccess/show/index.jsx
- src/contexts/confirmationDialogContext/index.jsx
In this PR:
- Adding remove access functionality to remove an agent's ACP-based access to a resource
> Feat: add remove button

- components/pages/privacy/resourceAccess/RevokeAccessButton/index.jsx
- components/pages/privacy/resourceAccess/RevokeAccessButton/styles.js
- components/pages/privacy/resourceAccess/resourceAccessDrawer/index.jsx
- components/pages/privacy/resourceAccess/resourceAccessDrawer/index.test.jsx
- components/pages/privacy/resourceAccess/show/index.jsx
- components/pages/privacy/resourceAccess/show/styles.js
- Added action menu with details/view resource and revoke access buttons
- Removed details action from entire row 
- Added details action to resource name only
_NOTE: Removing the details view trigger was necessary as it was causing unexpected results when clicking the action menu. Clicking the action menu would trigger the row click event and open the drawer while ignoring the action menu listener._
> Added action menu to agent resource access page

- components/addContact/index.jsx
- components/addContact/index.test.jsx
- src/addressBook/index.js
This PR fixes bug #1035.
- Try to add a new ESS 1.2 style WebID to Contacts
- You should get a success message and see the contact if you navigate back to the Contacts page
> Fix: allow contacts without name, type Agent

- components/resourceDetails/resourceSharing/agentAccessTable/index.jsx
- components/resourceDetails/resourceSharing/agentAccessTable/index.test.jsx
This PR fixes bug #SOLIDOS-1078.
Profiles without a name were causing an error when sorting the agents in the access table.
> Fix: handle profiles without names when sorting

- components/login/provider/index.jsx
This PR fixes bug #1082.
We weren't passing the client name in the auth options during registration in one spot. 
- Log in using an incognito window with dev next.
- Verify Inrupt PodBrowser is displayed in the auth screen instead of the long ID.
> Fix: pass client name to auth options

- components/consentRequestForm/__snapshots__/index.test.jsx.snap
- components/consentRequestForm/dateInput/index.jsx
- components/consentRequestForm/dateInput/index.test.jsx
- components/consentRequestForm/index.jsx
- components/consentRequestForm/purposeCheckBox/index.jsx
- components/consentRequestForm/styles.js
- components/pages/privacy/consent/requests/__snapshots__/index.test.jsx.snap
In this PR:
- we haven't implemented functionality to select purposes from a list and change expiration date of access grant, so we are temporarily disabling the UI related to these.
- update snapshots and skip relevant tests until interaction is reintroduced
This PR fixes bug #PB-1095.
> Fix: temporarily disable date picker and purposes checkboxes on Access Request UI

- components/deleteResourceButton/index.jsx
- next-env.d.ts
- src/accessControl/acp/index.js
- src/accessControl/acp/index.test.js
- tsconfig.json
This PR fixes bug #PB-1118.
In this PR: 
- Using the right legacy functions to get the permissions
- Using the right legacy functions in the test as well to add the policies to the policy resource (as this was causing our tests not to catch this at all)
- Log in with 1.1
- Verify that agents can be added to policies and are displayed correctly in the Sharing panel
> Fix: use legacy functions in 1.1 to get policies urls

- jest.config.js
This prevents jest from looking at the .next directory, which includes some copied test files.
> Ignore .next directory when testing

- components/pages/contacts/show/__snapshots__/index.test.jsx.snap
- components/pages/privacy/resourceAccess/show/__snapshots__/index.test.jsx.snap
- components/pages/privacy/resourceAccess/show/index.test.jsx
- components/pages/privacy/show/__snapshots__/index.test.jsx.snap
- components/profile/__snapshots__/index.test.jsx.snap
- components/profile/personAvatar/__snapshots__/index.test.jsx.snap
- components/profile/personAvatar/index.jsx
This PR fixes bug #APPS-1155.
We were incorrectly assuming the WebID and the profile IRI were the same. This PR changes that to using the WebID from the session.
> Fix: display WebID in profile instead of profile IRI

- components/contactsList/contactsDrawer/index.jsx
- components/contactsList/index.jsx
This PR fixes bug #APPS-1107.
The ConfirmationDialog was not added to the Drawer component and therefore not displayed. We previously attempted to display in in the App component, but this led to issues with testing, although we might want to revisit that idea in the future to avoid having to add the component to each component where it is used (and having these type of bugs).
> Fix: display confirmation dialog when clicking Delete contact button

- CODE-OF-CONDUCT.md
- README.md
This PR adds a Code of Conduct to PodBrowser. It is adapted from [Contributor Covenant](https://www.contributor-covenant.org/).
I am particularly interested in feedback regarding how to further adapt this to include behaviours and standards specific to our community, but of course all feedback is very much welcome.
> add Code of Conduct

- components/login/index.jsx
- package-lock.json
- package.json
This fixes three issues:
* Removes the use of OIDCPublicClient from localhost, which is being deprecated. Instead, localhost now uses dynamic client registration.
* Upgrades solid-client-authn, which now includes the webid OIDC scope.
* Fixes an issue in localhost developing against the latest dev version of ESS, causing an infinite loop due to an OIDC error.
> Remove public client; update solid-client-authn

- components/login/index.jsx
There has been an error during login where no client_id is being passed in to the login form. This fix provides the login form with the client_id if the login is oidc supported, otherwise it uses a default value.
> updated client_id logic

- __testUtils/mockLocalStorage.js
- components/pages/index/index.jsx
- src/hooks/usePreviousPage/index.js
- src/hooks/usePreviousPage/index.test.jsx
This clears the previousPage value from localstorage after it is read to clean up localstorage and prevent a looping bug.
> Clear previouspage out of localstorage after reading

- components/login/index.jsx
This PR makes sure that client_id is not sent in as a null value, but rather is omitted entirely if it should not be sent.
> Only send clientId if it has a value

- components/consentRequestForm/index.jsx
- components/consentRequestForm/styles.js
This PR fixes bug #1090.
Updated styling to help with overflowing content. Essentially the URIs are long strings, and the div looks for a white space to break it up. If there is no white space it run outside of the div. The word-break css attribute allows the string be broken into lines if necessary without the string containing whitespace.
> Consent form text overflow

- components/login/provider/index.jsx
- components/login/provider/index.test.jsx
This fixes an issue where pressing "enter" on the login form with a custom openid provider does not include the client id.
> Send client id when enter is pressed in the login form

- src/solidClientHelpers/utils.js
- src/solidClientHelpers/utils.test.js
This PR makes a small change to the namespaces code in the solid client utilities. It makes what the code is a little more clear by adding a named function which reveals the intent. The namespace map is meant to be a data structure for translating from "friendly" keys to corresponding namespace URLs and vice versa. This code makes that intent more clear from the code itself.
- Moved object key mirroring code into a function `mirrorKeysAndValues`
- Used `mirrorKeysAndValues` to shed some LOC
- Named the literal object representing the missing namespace urls
- Run the tests regularly `npm test`
- Verify they all pass
> Cleanup and clarify namespace utilities

- src/jest-solid/index.js
- src/jest-solid/toHaveRDFType.js
- src/jest-solid/toHaveRDFType.test.js
- src/jest-solid/toHaveString.js
- src/jest-solid/toHaveString.test.js
- src/jest-solid/toHaveURL.js
- src/jest-solid/toHaveURL.test.js
I thought it might be nice to have some jest helpers to clean up our expectations around `Thing`s. I've started a small expectation library to make testing things a little more straight forward.
- Added solid test helpers to our jest configuration
- Added an expectation to check if a thing contains a specific RDF type
- Added an expectation to check if a thing contains a specific URL predicate/value
- Added an expectation to check if a thing contains a specific String predicate/value
- run `npm test src/jest-solid`
- verify all tests pass
The following are some examples of these expectations in action:
```js
expect(thing).toHaveRDFType(foaf.Person)
expect(thing).toHaveURL(foaf.homepage)
expect(thing).toHaveURL(foaf.homepage, "https://example.com")
expect(thing).toHaveString(foaf.name) …
```
> Add jest expectations for solid things

- src/solidClientHelpers/utils.test.js
This PR adds tests to `solidClientHelpers/utils.js` to bring coverage up to 100%.
- Added a test to cover passing `undefined` to `isContainerIri`
- Added a test to cover `uniqueObjects`
- run `npm test src/solidClientHelpers/utils.test.js`
- verify all tests pass
- verify coverage is 100%
@VirginiaBalseiro @solid-akb 
captures
> Up test coverage of utils to 100%

- src/addressBook/index.js
- src/solidClientHelpers/utils.js
- src/solidClientHelpers/utils.test.js
As I've been working with the address book code I noticed that there was some extra juggling necessary to respond with the correct error message using `createResponder` in `src/solidClientHelpers/utils.js`. I pulled that logic out of address book and put it in the responder code.
- Refactored `addressBook.js` to use the refactored code
- Refactored `createResponder` to respond with an error function that can handle unauthorized requests
- run `npm test`
- verify all tests still pass
@VirginiaBalseiro @solid-akb @ajacksified 
I'm not 100% sold on this myself. It does seem like this code does not belong in `addressBook` (with the exception of the configurable message). It does seem like we might want to handle unauthorized requests like this in the error responder because it seems silly to …
> Refactor error responder to accept unauthorized message

- __testUtils/testApp.jsx
- __testUtils/withTheme.jsx
- components/consentRequestForm/requestSection/index.jsx
- components/groupDetails/groupDetailsModal/index.jsx
- components/resourceDetails/resourceSharing/addAgentButton/index.jsx
- components/resourceDetails/resourceSharing/advancedSharingButton/index.jsx
- components/resourceDetails/resourceSharing/agentAccess/agentProfileDetails/index.jsx
- components/resourceDetails/resourceSharing/agentAccess/index.jsx
- components/resourceDetails/resourceSharing/agentAccessOld/index.jsx
- components/resourceDetails/resourceSharing/agentPickerModal/addWebIdButton/index.jsx
- components/resourceDetails/resourceSharing/agentPickerModal/index.jsx
- components/resourceDetails/resourceSharing/agentPickerModal/webIdCheckbox/index.jsx
- components/resourceDetails/resourceSharing/agentsSearchBar/index.jsx
- components/resourceDetails/resourceSharing/index.jsx
- components/resourceDetails/resourceSharing/mobileAgentsSearchBar/index.jsx
- components/resourceDetails/resourceSharing/policiesDescriptions/index.jsx
- components/tabs/index.jsx
- constants/propTypes.js
- src/contexts/accessControlContext/index.jsx
- src/contexts/consentRequestContext/index.jsx
We used `eslint-disable-next-line react/forbid-prop-types` pretty gratuitously throughout the code. Removed the instance when it wasn't protecting anything and when we used T.Object. From now on we should use `T.oneOfType([Object])`
Deleted extra `eslint-disable-next-line react/forbid-prop-types` and replaced T.Object with `T.oneOfType([Object])` which does not throw a warning.
NA
- [ NA] All acceptance criteria are met.
- [ NA] Includes tests to ensure functionality and prevent regressions.
- [x ] Relevant documentation, if any, has been written/updated.
- [ NA] The changelog has been updated, if applicable.
Use `T.oneOfType([Object])` when you want to pass in an Object as a prop.
> Removed forbid prop types

- src/authentication/useReturnUrl.test.js
This PR removes `await` when using act in tests in the `useReturnUrl` hook because it was causing a console warning. 
`act` cannot be awaited unless used in its sync version: https://reactjs.org/docs/testing-recipes.html#act
> remove unnecessary await before act

- package-lock.json
Fix minimist vulnerability via npm audit fix.
There are also unrelated linting changed in the lock file which happen on the latest npm when running npm install.
> fix minimist vulnerability via npm audit fix

- __testUtils/testApp.jsx
- __testUtils/withTheme.jsx
- components/consentRequestForm/requestSection/index.jsx
- constants/propTypes.js
- src/contexts/consentRequestContext/index.jsx
Prop types that were Object changed back to oneOfType([Object]) because oneOfType([Object]) was breaking unit tests (and is incorrect). Revisit react/forbid-prop-types comments at a later time.
> changed PT to object and added eslint disable

- src/authentication/useReturnUrl.js
- src/authentication/useReturnUrl.test.js
I didn't realise `localStorage.setItem` could throw, but apparently it can, so this makes that error silent. This fixes POD-BROWSER-2D9 on Sentry.
Just adds a try/catch
Additional test case has been added.
> fix: ignore errors thrown from localstorage when persisting the returnTo URL

- pages/_app.jsx
- src/sentryFilter/index.js
- src/sentryFilter/index.test.js
This PR adds functionality to redact certain breadcrumbs that include sensitive information.
- Added a `sentryFilter` module to contain Sentry log filters
- Added a `listHelpers` module and added a partition function
- It's complicated
@solid-akb @VirginiaBalseiro 
This one is a bit harder to test than normal since we'll need to trigger the offending errors and then check Sentry to ensure that they've been redacted.
> Add filter to redact certain Sentry logs

- .github/workflows/ci.yml
- husky.config.js
- package.json
Node.js v12 is now end of life, and we only deploy to node v14; Also uses explicit steps for test and lint, rather than combining them
I've documented anything specific in the "files" tab via comments.
All tests ran fine
> Simplify CI configuration

- __testUtils/mockConsentRequestDetails.js
- components/consentRequestForm/index.jsx
- components/consentRequestForm/index.test.jsx
- components/pages/privacy/access/requests/index.test.jsx
- src/models/consent/request/index.js
- src/models/consent/request/index.test.js
- add check for resource owner WebID and redirect/display alert
- update tests and mock access requests
- go to https://test-app-access-grants.vercel.app/
- generate a request
- make sure you are logged in to PB with a WebID that is different from the resource owner you inputted on the demo app to generate the request
- once redirected, grab the section of the URL starting from privacy/...
- go to the Vercel deployment of this PR and append that to the URL
- verify a red toast is displayed and you are redirected to the main PB page
- log out of PB and log in as the resource owner
- navigate to the request page again (use the same one you used before)
- verify you can see the request and everything works as intended
> Feat: redirect user to main page if not data subject of access request

- components/container/__snapshots__/index.test.jsx.snap
- components/podIndicator/index.jsx
- components/resourceDetails/__snapshots__/index.test.jsx.snap
- components/resourceDetails/index.jsx
- components/resourceDetails/index.test.jsx
- components/resourceDrawer/__snapshots__/index.test.jsx.snap
Now you can copy your resource address in PB. 
New copy link button on Resource Details Drawer
Navigate to a container or resource in your pod. Click on the open area next to the name. The details drawer should open to the right. Click on "COPY LINK" and your resource/container address will be saved to your clipboard. 
- [ x] All acceptance criteria are met.
- [ x] Includes tests to ensure functionality and prevent regressions.
- [x ] Relevant documentation, if any, has been written/updated.
@VirginiaBalseiro @KyraAssaad @ThisIsMissEm 
https://user-images.githubusercontent.com/94387648/162857823-a684b1c9-a113-4dd3-9190-ecb906cc58db.mov
> Copy resource link

- components/accessRequestForm/index.jsx
In this PR: setting date to just before midnight when selecting a new expiration date using the date picker.
Generate a request. Using the vercel deployment for this PR, change the expiration date and verify that the correct date is reflected on the grant once approved and redirected.
> set time to just before midnight when selecting expiration date

- components/accessRequestForm/index.jsx
In this PR: accepting an access request without a purpose
- Generate a request without a purpose (@matthieubosquet using your demo app or tweaking the existing demo app)
- Use the Vercel deployment for this PR to display the request on PB (replace the corresponding path on the URL)
- verify that you can approve a request without issues and the grant reflects that lack of purpose
> accept a request with no purpose

- components/accessRequestForm/index.jsx
This PR fixes the issue described in https://github.com/inrupt/pod-browser/pull/491/files#r893842855
However, setting date to "forever" won't change the expiration date on the grant because of a bug on the SDK. Since there is still discussion as to how to handle that, one proposed solution was to distinguish `null` from `undefined` values for expiration date, so I have explicitly set this to null if no date is selected. We can revisit this when that issue is solved.
> handle case where no date is selected

- components/container/index.jsx
- components/container/index.test.jsx
- components/header/index.test.jsx
- components/header/userMenu/index.jsx
- components/header/userMenu/index.test.jsx
- components/pages/privacy/resourceAccess/show/index.jsx
- components/pages/privacy/resourceAccess/show/index.test.jsx
- components/podIndicator/index.jsx
- src/hooks/useAddressBook/index.js
- src/hooks/useAddressBook/index.test.js
- src/hooks/useAddressBookOld/index.js
- src/hooks/useAuthenticatedProfile/index.js
- src/hooks/useAuthenticatedProfile/index.test.jsx
- src/hooks/useBookmarks/index.js
- src/hooks/useBookmarks/index.test.jsx
- src/hooks/useContactsContainerUrl/index.js
- src/hooks/useContactsContainerUrl/index.test.js
- src/hooks/usePodBrowserSettings/index.js
- src/hooks/usePodBrowserSettings/index.test.jsx
- src/hooks/usePodRootUri/index.js
- src/hooks/usePodRootUri/index.test.jsx
The `useAuthenticatedHook` was using an old fetch profile function that defaults to an extended profile if available, ignoring the WebID profile, and therefore missing the storage, which is why PB was hanging because no pod was available.
> use new profile function in auth profile hook

- __testUtils/mockPersonResource.js
- components/header/__snapshots__/index.test.jsx.snap
- components/header/index.test.jsx
- components/header/userMenu/__snapshots__/index.test.jsx.snap
- components/header/userMenu/index.jsx
- components/header/userMenu/index.test.jsx
- components/pages/profile/index.jsx
- components/profile/contactInfoTable/index.jsx
- components/profile/contactInfoTable/index.test.jsx
- components/profile/editableProfile/index.jsx
- components/profile/editableProfile/index.test.jsx
- components/profile/personAvatar/index.jsx
- components/profile/personProfile/index.jsx
- src/solidClientHelpers/profile.js
- src/solidClientHelpers/profile.test.js
This PR: 
- introduces a change in the `getFullProfile` function: when a Thing with WebID as subject cannot be found, one is created and added to the dataset (all of the editable datasets) so that we can use the WebID as Thing URL in the Context wrapping the Profile page.
- simplifies the `getFullProfile` function
- add tests
- Create a new account and edit profile on prod PB
- Verify the profile contains wrong triples (profile dataset URL as subject instead of WebID)
- Log in on the deployment of this branch and edit profile
- verify a triple has been added with WebID as subject
> add new thing with correct subject if not available

- components/container/index.jsx
- components/downloadLink/index.jsx
- components/downloadLink/index.test.jsx
- components/downloadResourceMessage/__snapshots__/index.test.jsx.snap
- components/downloadResourceMessage/index.jsx
- components/downloadResourceMessage/index.test.jsx
- components/downloadResourceMessage/styles.js
- components/resourceDetails/styles.js
- components/resourceDrawer/index.jsx
- src/hooks/useAccessToResourceAndParentContainer/index.jsx
- src/hooks/useAccessToResourceAndParentContainer/index.test.jsx
When navigating to a resource to which a user has access (by any means, including authenticated agent) but does not have access to parent container, PodBrowser tried to load the parent container and incorrectly rendered an error saying the user has no access to the resource.
This PR changes that by checking what the user's access is to both resource and parent container, and either triggering a download and isplaying a download message, or rendering an error if user truly does not have access to the resource.
1. Log in as User A, share a resource with Anyone
2. Log in as User 2, try to navigate to the resource via the Pod Navigator
3. Verify that a download starts and a download message is displayed
4. Verify that the no access error is displayed by repeating the above steps with a …
> download resource

- components/container/index.jsx
- components/header/userMenu/index.jsx
- components/header/userMenu/index.test.jsx
- components/noPodFoundError/__snapshots__/index.test.jsx.snap
- components/noPodFoundError/index.jsx
- components/noPodFoundError/index.test.jsx
- components/noPodFoundError/styles.js
- components/pages/index/__snapshots__/index.test.jsx.snap
- components/pages/index/index.test.jsx
- components/pages/profile/index.jsx
- components/pages/resource/__snapshots__/index.test.jsx.snap
- components/pages/resource/index.test.jsx
- components/permissionsForm/index.test.jsx
- components/profile/editableProfile/index.jsx
- components/profile/personAvatar/index.jsx
- constants/propTypes.js
- src/hooks/useBookmarks/index.js
- src/hooks/usePodRootUri/index.js
- src/hooks/usePodRootUri/index.test.jsx
- src/solidClientHelpers/profile.js
Whenever PB cannot find a Pod URL in the profile, it completely hangs. Instead we want to display an error to users. If an extended profile cannot be fetched, we want the function retrieving the profile to ignore this and move on.
This PR introduces a fix to handle the case where a Pod URL cannot be found on a profile, and also fixes a bug where `getFullProfile` was not handling failing to fetch an extended profile dataset properly (ignoring the error and moving on).
I took some design liberties (error messages) so design review is required.
Case 1: fail to fetch an extended profile
1. https://id.inrupt.com/ edit your WebID by changing the URLs to the extended profile (highlighted in screenshot below)
2. Go to the Vercel deployment of this branch (Preview) and verify everything works …
> handle no pod URL and error fetching extended profile properly

- components/containerTable/__snapshots__/index.test.jsx.snap
- components/containerTable/index.jsx
Just make 'folder' terminology consistent with the rest of the UI (i.e., 'FOLDER DETAILS', 'CREATE FOLDER' buttons, etc.).
Message updated to use the term 'folder' instead of 'container'.
All tests pass.
> Use the term folder consistently in UI messaging

- components/accessRequestForm/index.jsx
Clean up of code. 
The SDK removed the argument of the resourceOwner from their code. This change is now reflected in PodBrowser where we remove the resourceOwner from the argument list when calling `approveAccessRequest` and `denyAccessRequest` 
Start the request access flow. 
Get re-routed to PodBrowser (make sure the reroute brings you to localhost PB and not prod PB, you can update the URL to reflect this too)
Accept Request. 
Login to PodBrowser as the requesting user. 
In the upper right corner where it says "change pod", put in the resource URI that you requested access to. 
CHECK IF YOU HAVE ACCESS. If yes it worked.  
Start the request access flow again, use the same resource that you just confirmed you have access to. 
Get re-routed to PB. Again confirm you are in localhost and …
> removed webID from accept deny funcs

- components/accessRequestForm/index.jsx
- components/accessRequestForm/index.test.jsx
This PR fixes the issue where `denyAccessRequest` was not being called with an options object, causing it to fail. PodBrowser is still at access grants `1.0.1`, so this fixes the issue at the current version and we can look into upgrading separately, as it introduces other challenges.
> pass fetch fn to deny function
